server:
  port: 8082

spring:
  application:
    name: service-newsfeed
  datasource:
    url: jdbc:postgresql://localhost:5432/newsfeed
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/