spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: jeff.hyjo@gmail.com
    password: cnfbljprghlkfykk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

  redis:
    host: localhost
    port: 6378

  datasource:
    url: jdbc:postgresql://postgres:5432/scdb
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver

