server:
  port: 8081

spring:
  application:
    name: service-activity
  datasource:
    url: jdbc:postgresql://postgres:5432/activity
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000