server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-user
          uri: lb://SERVICE-USER
          predicates:
            - Path=/users/**

        - id: service-activity
          uri: lb://SERVICE-ACTIVITY
          predicates:
            - Path=/contents/**

        - id: service-newsfeed
          uri: lb://SERVICE-NEWSFEED
          predicates:
            - Path=/feeds/**

        - id: service-shop
          uri: lb://SERVICE-SHOP
          predicates:
            - Path=/shop/**