version: '3'

services:
  postgres:
    container_name: postgres_user
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: scdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234

  adminer:
    container_name: adminer_user
    image: adminer
    restart: always
    ports:
      - 8090:8080
    depends_on:
      - postgres

  redis:
    container_name: redis_user
    image: redis:latest
    ports:
      - 6378:6379

  application:
    container_name: user_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/scdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
