version: '3'

services:
  application:
    container_name: eureka-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    environment:
      eureka.instance.hostname: eureka-server
      eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/