version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: newsfeed
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234

  adminer:
    image: adminer
    restart: always
    ports:
      - 8092:8080
    depends_on:
      - postgres

  application:
    container_name: newsfeed
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/newsfeed
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
