server:
  port: 8084
spring:
  application:
    name: service-shop
  redis:
    host: localhost
    port: 6378

  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000